// Hard-difficulty tasks from the Industry Task Masterlist, grouped by site category.
// Only "Hard" tasks are included -- Easy/Medium tasks are filtered out at the source.
export interface MasterTask {
  id: string;
  name: string;
}

export const TASKS_BY_CATEGORY: Record<string, MasterTask[]> = {
  'Retail and Consumer Goods': [
    { id: 'retail_appliance_demo_and_handover', name: 'Appliance demo and handover' },
    { id: 'retail_butcher_shop_counter', name: 'Butcher shop counter' },
    { id: 'retail_butchery_and_portioning', name: 'Butchery and portioning' },
    { id: 'retail_in_store_bakery_production', name: 'In-store bakery production' },
    { id: 'retail_inventory_management', name: 'Inventory management' },
    { id: 'retail_perfume_consultation_and_blending', name: 'Perfume consultation and blending' },
    { id: 'retail_planogram_reset', name: 'Planogram reset' },
    { id: 'retail_rug_appraisal_and_handling', name: 'Rug appraisal and handling' },
    { id: 'retail_store_equipment_maintenance', name: 'Store equipment maintenance' },
  ],
  'Fashion': [
    { id: 'fashion_beading_and_embellishment', name: 'Beading and embellishment' },
    { id: 'fashion_bespoke_measurement_and_draping', name: 'Bespoke measurement and draping' },
    { id: 'fashion_complex_tailoring', name: 'Complex tailoring' },
    { id: 'fashion_embroidery_programming', name: 'Embroidery programming' },
    { id: 'fashion_garment_construction', name: 'Garment construction' },
    { id: 'fashion_leather_garment_work', name: 'Leather garment work' },
    { id: 'fashion_pattern_making_and_cutting', name: 'Pattern making and cutting' },
    { id: 'fashion_rug_and_textile_restoration', name: 'Rug and textile restoration' },
    { id: 'fashion_screen_printing_apparel', name: 'Screen printing apparel' },
  ],
  'Repair Services': [
    { id: 'repair_antique_restoration_repair', name: 'Antique restoration repair' },
    { id: 'repair_appliance_major_repair', name: 'Appliance major repair' },
    { id: 'repair_boat_engine_service', name: 'Boat engine service' },
    { id: 'repair_circuit_level_electronics_repair', name: 'Circuit-level electronics repair' },
    { id: 'repair_data_recovery_workflow', name: 'Data recovery workflow' },
    { id: 'repair_electromechanical_rebuilds', name: 'Electromechanical rebuilds' },
    { id: 'repair_instrument_repair', name: 'Instrument repair' },
    { id: 'repair_locksmithing', name: 'Locksmithing' },
    { id: 'repair_screen_remanufacturing', name: 'Screen remanufacturing' },
    { id: 'repair_watch_movement_service', name: 'Watch movement service' },
  ],
  'Food and Beverage': [
    { id: 'fnb_advanced_cake_artistry', name: 'Advanced cake artistry' },
    { id: 'fnb_butchery_and_filleting', name: 'Butchery and filleting' },
    { id: 'fnb_fermentation_program', name: 'Fermentation program' },
    { id: 'fnb_kitchen_equipment_deep_clean', name: 'Kitchen equipment deep clean' },
    { id: 'fnb_latte_art_and_dial_in_mastery', name: 'Latte art and dial-in mastery' },
    { id: 'fnb_menu_development_testing', name: 'Menu development testing' },
    { id: 'fnb_multi_dish_service_coordination', name: 'Multi-dish service coordination' },
    { id: 'fnb_pastry_production', name: 'Pastry production' },
    { id: 'fnb_scratch_production', name: 'Scratch production' },
    { id: 'fnb_wok_station_high_heat_cooking', name: 'Wok station high-heat cooking' },
  ],
  'Construction and Hardware': [
    { id: 'constr_blueprint_interpretation_and_build', name: 'Blueprint interpretation and build' },
    { id: 'constr_cabinet_installation', name: 'Cabinet installation' },
    { id: 'constr_concrete_formwork', name: 'Concrete formwork' },
    { id: 'constr_electrical_installation', name: 'Electrical installation' },
    { id: 'constr_electrical_service_work', name: 'Electrical service work' },
    { id: 'constr_finish_carpentry', name: 'Finish carpentry' },
    { id: 'constr_plumbing_rough_in', name: 'Plumbing rough-in' },
    { id: 'constr_renovation_demolition_and_prep', name: 'Renovation demolition and prep' },
    { id: 'constr_structural_framing', name: 'Structural framing' },
    { id: 'constr_tiling_and_waterproofing', name: 'Tiling and waterproofing' },
    { id: 'constr_welding_structural_elements', name: 'Welding structural elements' },
  ],
  'Food Processing': [
    { id: 'foodproc_cheese_affinage', name: 'Cheese affinage' },
    { id: 'foodproc_fermentation_and_curing', name: 'Fermentation and curing' },
    { id: 'foodproc_haccp_monitoring_and_records', name: 'HACCP monitoring and records' },
    { id: 'foodproc_machine_changeover_and_maintenance', name: 'Machine changeover and maintenance' },
    { id: 'foodproc_meat_cutting_and_deboning', name: 'Meat cutting and deboning' },
    { id: 'foodproc_production_scheduling', name: 'Production scheduling' },
    { id: 'foodproc_quality_lab_checks', name: 'Quality lab checks' },
    { id: 'foodproc_roast_profiling', name: 'Roast profiling' },
    { id: 'foodproc_sanitation_and_cip', name: 'Sanitation and CIP' },
  ],
  'Printing and Design': [
    { id: 'print_channel_letter_fabrication', name: 'Channel letter fabrication' },
    { id: 'print_color_calibration_and_proofing', name: 'Color calibration and proofing' },
    { id: 'print_custom_frame_joinery', name: 'Custom frame joinery' },
    { id: 'print_foiling_and_specialty_finishing', name: 'Foiling and specialty finishing' },
    { id: 'print_large_format_installation', name: 'Large-format installation' },
    { id: 'print_multi_color_screen_printing', name: 'Multi-color screen printing' },
    { id: 'print_prepress_and_imposition', name: 'Prepress and imposition' },
    { id: 'print_vehicle_wrap_installation', name: 'Vehicle wrap installation' },
  ],
  'Factory': [
    { id: 'factory_fpc_production_processes', name: 'FPC production processes' },
    { id: 'factory_injection_molding_process_control', name: 'Injection molding process control' },
    { id: 'factory_line_supervision', name: 'Line supervision' },
    { id: 'factory_machine_setup_and_calibration', name: 'Machine setup and calibration' },
    { id: 'factory_maintenance_troubleshooting', name: 'Maintenance troubleshooting' },
    { id: 'factory_quality_system_audits', name: 'Quality system audits' },
    { id: 'factory_tool_and_die_maintenance', name: 'Tool and die maintenance' },
    { id: 'factory_welding_and_fabrication_cell', name: 'Welding and fabrication cell' },
  ],
  'Hospitality': [
    { id: 'hotel_banquet_service_captaincy', name: 'Banquet service captaincy' },
    { id: 'hotel_event_setup_management', name: 'Event setup management' },
    { id: 'hotel_housekeeping_supervision', name: 'Housekeeping supervision' },
    { id: 'hotel_laundry_system_management', name: 'Laundry system management' },
    { id: 'hotel_maintenance_repair', name: 'Maintenance repair' },
    { id: 'hotel_pool_plant_maintenance', name: 'Pool plant maintenance' },
    { id: 'hotel_preventive_maintenance_rounds', name: 'Preventive maintenance rounds' },
    { id: 'hotel_revenue_and_rooms_admin', name: 'Revenue and rooms admin' },
  ],
  'Automotive and Transport': [
    { id: 'auto_a_c_system_service', name: 'A/C system service' },
    { id: 'auto_body_dent_and_scratch_repair', name: 'Body dent and scratch repair' },
    { id: 'auto_electrical_fault_tracing', name: 'Electrical fault tracing' },
    { id: 'auto_engine_diagnostics_and_repair', name: 'Engine diagnostics and repair' },
    { id: 'auto_forklift_operations', name: 'Forklift operations' },
    { id: 'auto_paint_correction_and_coating', name: 'Paint correction and coating' },
    { id: 'auto_suspension_and_steering', name: 'Suspension and steering' },
    { id: 'auto_transmission_and_clutch_work', name: 'Transmission and clutch work' },
    { id: 'auto_wheel_alignment', name: 'Wheel alignment' },
  ],
  'Sports and Recreation': [
    { id: 'sport_bike_fitting_and_build', name: 'Bike fitting and build' },
    { id: 'sport_climbing_wall_route_setting', name: 'Climbing wall route setting' },
    { id: 'sport_fitness_equipment_repair', name: 'Fitness equipment repair' },
    { id: 'sport_grounds_maintenance_program', name: 'Grounds maintenance program' },
    { id: 'sport_pool_systems_management', name: 'Pool systems management' },
    { id: 'sport_strength_coaching_session', name: 'Strength coaching session' },
    { id: 'sport_turf_renovation', name: 'Turf renovation' },
  ],
  'Creative Workshops': [
    { id: 'craft_furniture_reupholstery', name: 'Furniture reupholstery' },
    { id: 'craft_grout_and_installation_of_mosaics', name: 'Grout and installation of mosaics' },
    { id: 'craft_kiln_firing_management', name: 'Kiln firing management' },
    { id: 'craft_leather_bag_construction', name: 'Leather bag construction' },
    { id: 'craft_metalsmithing', name: 'Metalsmithing' },
    { id: 'craft_stained_glass_fabrication', name: 'Stained glass fabrication' },
    { id: 'craft_wheel_throwing_and_kiln_work', name: 'Wheel throwing and kiln work' },
    { id: 'craft_wheel_throwing_production', name: 'Wheel throwing production' },
  ],
  'Administrative': [
    { id: 'admin_board_meeting_logistics', name: 'Board meeting logistics' },
    { id: 'admin_facilities_coordination', name: 'Facilities coordination' },
    { id: 'admin_meeting_room_av_setup', name: 'Meeting-room AV setup' },
    { id: 'admin_records_management', name: 'Records management' },
    { id: 'admin_vendor_contract_administration', name: 'Vendor contract administration' },
  ],
  'Education and Training': [
    { id: 'edu_archive_digitization', name: 'Archive digitization' },
    { id: 'edu_cataloging_and_preservation', name: 'Cataloging and preservation' },
    { id: 'edu_practical_assessment_running', name: 'Practical assessment running' },
    { id: 'edu_science_practical_preparation', name: 'Science practical preparation' },
    { id: 'edu_trade_demonstration_work', name: 'Trade demonstration work' },
  ],
  'Industrial Manufacturing': [
    { id: 'mfg_cnc_machining_setup', name: 'CNC machining setup' },
    { id: 'mfg_garment_fit_session', name: 'Garment fit session' },
    { id: 'mfg_industrial_machine_maintenance', name: 'Industrial machine maintenance' },
    { id: 'mfg_metal_fabrication', name: 'Metal fabrication' },
    { id: 'mfg_pattern_grading_and_markers', name: 'Pattern grading and markers' },
    { id: 'mfg_smt_line_setup', name: 'SMT line setup' },
    { id: 'mfg_sample_making', name: 'Sample making' },
    { id: 'mfg_tig_welding_precision_work', name: 'TIG welding precision work' },
    { id: 'mfg_test_and_burn_in_station', name: 'Test and burn-in station' },
  ],
  'Energy and Utilities': [
    { id: 'energy_backup_power_commissioning', name: 'Backup power commissioning' },
    { id: 'energy_chlorination_system_service', name: 'Chlorination system service' },
    { id: 'energy_motor_control_center_work', name: 'Motor control center work' },
    { id: 'energy_pump_teardown_and_rebuild', name: 'Pump teardown and rebuild' },
    { id: 'energy_solar_or_electrical_installation', name: 'Solar or electrical installation' },
    { id: 'energy_switchgear_maintenance', name: 'Switchgear maintenance' },
    { id: 'energy_water_quality_and_dosing', name: 'Water quality and dosing' },
  ],
  'Healthcare and Pharmacy': [
    { id: 'health_chairside_dental_assisting', name: 'Chairside dental assisting' },
    { id: 'health_compounding_preparations', name: 'Compounding preparations' },
    { id: 'health_dental_prosthetics_work', name: 'Dental prosthetics work' },
    { id: 'health_diagnostic_testing', name: 'Diagnostic testing' },
    { id: 'health_pharmacy_inventory_control', name: 'Pharmacy inventory control' },
    { id: 'health_pharmacy_verification_workflow', name: 'Pharmacy verification workflow' },
    { id: 'health_sterile_technique_compounding', name: 'Sterile technique compounding' },
    { id: 'health_suture_assist_workflow', name: 'Suture assist workflow' },
    { id: 'health_treatment_procedures', name: 'Treatment procedures' },
  ],
  'Administrative & Office Services': [
    { id: 'offsvc_it_hardware_deployment', name: 'IT hardware deployment' },
    { id: 'offsvc_office_equipment_servicing', name: 'Office equipment servicing' },
    { id: 'offsvc_print_fleet_management', name: 'Print fleet management' },
    { id: 'offsvc_server_room_basics', name: 'Server room basics' },
  ],
  'Cleaning and Sanitation': [
    { id: 'clean_biohazard_safe_cleaning', name: 'Biohazard-safe cleaning' },
    { id: 'clean_building_cleaning_management', name: 'Building cleaning management' },
    { id: 'clean_carpet_extraction', name: 'Carpet extraction' },
    { id: 'clean_floor_strip_and_wax', name: 'Floor strip and wax' },
    { id: 'clean_industrial_kitchen_sanitation', name: 'Industrial kitchen sanitation' },
    { id: 'clean_pressure_washing_services', name: 'Pressure washing services' },
    { id: 'clean_stain_treatment_expertise', name: 'Stain treatment expertise' },
  ],
  'Laboratory / Scientific': [
    { id: 'lab_analytical_method_transfer', name: 'Analytical method transfer' },
    { id: 'lab_cell_culture_workflows', name: 'Cell culture workflows' },
    { id: 'lab_chromatography_operations', name: 'Chromatography operations' },
    { id: 'lab_instrument_maintenance', name: 'Instrument maintenance' },
    { id: 'lab_method_validation_runs', name: 'Method validation runs' },
    { id: 'lab_specialized_protocols', name: 'Specialized protocols' },
  ],
  'Childcare and Caregiving': [
    { id: 'care_care_documentation_and_planning', name: 'Care documentation and planning' },
    { id: 'care_developmental_observation_records', name: 'Developmental observation records' },
    { id: 'care_individualized_support_routines', name: 'Individualized support routines' },
    { id: 'care_mobility_transfer_assistance', name: 'Mobility transfer assistance' },
  ],
  'Public Safety and Emergency Response': [
    { id: 'safety_equipment_maintenance', name: 'Equipment maintenance' },
    { id: 'safety_extrication_tool_servicing', name: 'Extrication tool servicing' },
    { id: 'safety_ladder_testing', name: 'Ladder testing' },
    { id: 'safety_pump_operation_testing', name: 'Pump operation testing' },
    { id: 'safety_training_evolutions', name: 'Training evolutions' },
  ],
  'Agriculture and Farming': [
    { id: 'agri_coconut_or_crop_processing', name: 'Coconut or crop processing' },
    { id: 'agri_crop_management_decisions', name: 'Crop management decisions' },
    { id: 'agri_equipment_operation', name: 'Equipment operation' },
    { id: 'agri_hatchery_and_brooding_care', name: 'Hatchery and brooding care' },
    { id: 'agri_pest_and_disease_program', name: 'Pest and disease program' },
    { id: 'agri_propagation_and_grafting', name: 'Propagation and grafting' },
    { id: 'agri_pruning_fruit_trees', name: 'Pruning fruit trees' },
    { id: 'agri_skilled_livestock_workflows', name: 'Skilled livestock workflows' },
    { id: 'agri_soil_preparation_program', name: 'Soil preparation program' },
  ],
  'Beauty and Personal Care': [
    { id: 'beauty_advanced_spa_treatments', name: 'Advanced spa treatments' },
    { id: 'beauty_barbering_razor_work', name: 'Barbering razor work' },
    { id: 'beauty_color_and_chemical_services', name: 'Color and chemical services' },
    { id: 'beauty_facial_treatment_protocols', name: 'Facial treatment protocols' },
    { id: 'beauty_haircut_and_styling', name: 'Haircut and styling' },
    { id: 'beauty_keratin_and_smoothing_systems', name: 'Keratin and smoothing systems' },
    { id: 'beauty_nail_extensions_and_art', name: 'Nail extensions and art' },
    { id: 'beauty_scalp_and_trichology_services', name: 'Scalp and trichology services' },
  ],
  'Entertainment and Events': [
    { id: 'event_follow_spot_and_show_ops', name: 'Follow spot and show ops' },
    { id: 'event_lighting_rig_and_focus', name: 'Lighting rig and focus' },
    { id: 'event_pyro_and_effects_prep', name: 'Pyro and effects prep' },
    { id: 'event_rigging_systems_work', name: 'Rigging systems work' },
    { id: 'event_set_construction', name: 'Set construction' },
    { id: 'event_sound_system_tuning', name: 'Sound system tuning' },
    { id: 'event_stage_management_calling', name: 'Stage management calling' },
  ],
  'Other': [
    { id: 'other_unlisted_skilled_real_work', name: 'Unlisted skilled real work' },
  ],
};
